// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = 0;

var CommandLineArgs = 0;

exports.Utils = Utils;
exports.CommandLineArgs = CommandLineArgs;
/* No side effect */
