// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_oo_curry = require('bs-platform/lib/js/caml_oo_curry.js');

require('colors');

function printResumeResults(data) {
  var tmp = Caml_oo_curry.js1(131142924, 2, tmp$1);
  var tmp$1 = Caml_oo_curry.js1(-498902297, 1, data);
  console.log(Caml_oo_curry.js1(-1055161979, 3, tmp));
  return /* () */ 0;
}

exports.printResumeResults = printResumeResults;
/*  Not a pure module */
