// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Config = require('./config');
var CommandLineArgs = require('command-line-args');

function getCommandLineArgs() {
  return CommandLineArgs(Config.cmdLineOptions);
}

console.log(CommandLineArgs(Config.cmdLineOptions));

exports.getCommandLineArgs = getCommandLineArgs;
/*  Not a pure module */
